### PR TITLE
style revisions

### PR DESCRIPTION
**Pull request by pcsandford**
@mmeiers please review. I have made some style changes to match the new layout, mainly line height, font-size and positioning. Also removed reference to the current event date in the html. Thanks!

### CODE REVIEW

**Comment by stulees** [comment]
@pcsandford Still need to include myself and @donnapep in these PRs, thanks. In doing a review, you've removed the `main--eventDate` list item in `index.html` but you haven't removed any code that still currently looks to set its content in `current.js`.

**Comment by pcsandford** [comment]
@stulees @donnapep sorry, I meant to add you at the end and say that I was planning on going through the current.js to remove the reference to that as a separate PR, but in retrospect there is probably not a lot in current.js that does need to be removed so I should have done it in this one. Sorry!

**Comment by mmeiers** [comment]
:+1: css and html look good

**Comment by pcsandford** [comment]
@mmeiers thanks! @stulees @donnapep please review the commit I added to remove references to the main event date in current.js. Thanks!

**Comment by stulees** [comment]
@pcsandford No worries, last commit looks good :+1:

**Comment by mmeiers** [comment]
:ok_hand:

**Comment by stulees** [comment]
@pcsandford Actually spoke too soon. Did you try running a build? I think you're going to need to remove this line - https://github.com/Rise-Vision/content-event-current-day/blob/master/src/js/current.js#L35

**Comment by pcsandford** [comment]
@stulees @mmeiers thanks!

**Comment by stulees** [comment]
@pcsandford And this one - https://github.com/Rise-Vision/content-event-current-day/blob/master/src/js/current.js#L38 . The `suffix` var isn't needed now and when you run a build, the lint check will likely complain about it.

**Comment by pcsandford** [comment]
@stulees ah ok thanks, I will remove those and run a build to test.

**Comment by pcsandford** [comment]
@stulees I ran the build and it also wanted me to remove current = moment(), as current was no longer being used. I ran the build again and it went ok. Thanks!

@donnapep FYI

**Comment by stulees** [comment]
@pcsandford Great. We'll get circle ci setup at some point to ensure a build gets run when a PR is created so it catches these things in case running a build locally first is forgotten. Might want to squash these commits too, otherwise :+1:

**Comment by pcsandford** [comment]
@stulees thanks! Good idea, and I will try and squash these 3 into 1 :)

**Pull request merged**
