### PR TITLE
Implementing Next Event section

### PR DESCRIPTION
**Pull request by stulees**
- Cleaned up Current section in regards to applying content
- Adding logic and applying content to Next Event section
- Putting `_getTodaysEvents` function in `theme-events.js` so it can be used by Current and Next object/sections

### CODE REVIEW

**Comment by stulees** [comment]
@pcsandford @donnapep Please review, thanks.

**Comment by donnapep** [comment]
@stulees It looks like there's some code duplication between `current.js` and `next.js`. Could some of these functions be written once in `theme-events.js` and have parameters passed to them for customization? Thx.

**Comment by stulees** [comment]
@donnapep I've created `common.js` to house common code across each area. Please review last commit, thanks. @pcsandford FYI

**Comment by donnapep** [comment]
@stulees That looks good! :+1:

**Comment by pcsandford** [comment]
@donnapep @stulees thank you both! :)

**Pull request merged**
