### PR TITLE
Implementing Current Event area

### PR DESCRIPTION
**Pull request by stulees**
- Adding `current.js` to manage initializing the Current event area and also updating it based on the array of events passed in
- `index.html` updated to remove hard coded values pertaining to Current Event area
- `theme-events.js` updated to manage instance of Current object/section

### CODE REVIEW

**Comment by stulees** [comment]
@pcsandford Please review, thanks. Will continue on to the Next Event section

**Comment by pcsandford** [comment]
@stulees thanks! Looks great. I will run the theme and check it out so far. Everything yesterday worked well through gulp build and getting the link from the dist file in storage. Thanks!

**Comment by donnapep** [comment]
@pcsandford @stulees I think I should be part of the review process for code changes. Would you agree? Thx.

**Comment by stulees** [comment]
@donnapep Totally right, apologies! Can you review this one? I will also make sure to mention you on the next PR

**Comment by donnapep** [comment]
@stulees :+1: Only suggestion I have would be to consider using the HTML template tag for the event data so that the HTML stays in `index.html` and is not embedded in the JS. Thx.

**Pull request merged**
